// flow-typed signature: 0c2177f8c50270c2c8ed1b72c3f065ad
// flow-typed version: <<STUB>>/autobind-decorator_v^1.3.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autobind-decorator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'autobind-decorator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autobind-decorator/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autobind-decorator/lib/index.js' {
  declare module.exports: $Exports<'autobind-decorator/lib/index'>;
}
